export default {
    //url:"https://santeproxy.org/ScriptsBraMedTest/" , 
    url:"https://santeproxy.org/ScriptsBraMedTest/" , 
    urlUtilisateurs : "ScriptListeUtilisateurs.php",
    urlClients:"ScriptListeClients.php",
    urlStocks:"ScriptListeStocks.php",
    urlProduitsStock:"ScriptListeStockProduits.php",
    urlProduits:"ScriptListeProduits.php",
    urlFactureClient:"ScriptListeFacturesClient.php",
    utilisateur:null,
    listeClients:null,
    listeStocks:null,
    listeProduitsStock:null,
    listeProduits:null,
    listeProduitsAjoutes:[],
    totalFacture:0,
    versement:0,
    selectedClient:null,
    width:0,
};